# 1. 사용하지 않을 규칙 목록 비활성화
disabled_rules:
  - trailing_whitespace  # 줄 끝의 불필요한 공백을 검사하지 않음
  - line_length          # 줄 길이 제한 없음

# 2. 선택적으로 활성화할 규칙 (기본적으로 비활성화됨)
opt_in_rules:
  - empty_count          # .isEmpty 대신 .count == 0 사용 금지
  - sorted_imports       # import 순서 자동 정렬
  - missing_docs         # 공개 API에 문서 주석(`///`) 없으면 경고

# 3. 특정 폴더 및 파일 설정
included:
  - Sources              # SwiftLint가 검사할 폴더 (Sources 내부 파일만 검사)
excluded:
  - Carthage            # 서드파티 라이브러리 폴더는 검사에서 제외
  - Pods                # CocoaPods 패키지는 검사에서 제외
  - DerivedData         # Xcode에서 생성하는 캐시 파일 검사 제외
  - Sources/ExcludedFolder  # 특정 폴더 제외 가능
  - Sources/ExcludedFile.swift  # 특정 파일 제외 가능

# 4. 코드 스타일 강제 규칙 (warning or error 설정)
force_cast: warning      # `as!` 강제 다운캐스팅 시 경고 발생
force_try: warning       # `try!` 강제 오류 처리 시 경고 발생

# 5. 코드 길이 관련 규칙
file_length:
  warning: 500          # 파일이 500줄 이상이면 경고
  error: 1200           # 파일이 1200줄 이상이면 에러 발생

type_body_length:
  warning: 300          # 클래스 또는 구조체의 최대 길이 (300줄 초과 시 경고)
  error: 400            # 400줄 초과 시 에러 발생

# 6. 네이밍 규칙 (변수, 함수, 타입 이름 길이)
type_name:
  min_length: 4         # 최소 4자 이상 (경고)
  max_length:
    warning: 40        # 40자 초과 시 경고
    error: 50         # 50자 초과 시 에러
  excluded: iPhone     # 특정 이름은 예외 처리 가능

identifier_name:
  min_length:
    error: 3          # 변수나 함수명이 3자 미만이면 에러 발생
  excluded:
    - id              # `id` 같은 일반적인 약어는 예외 처리
    - URL             # URL 같은 표준 명칭은 예외 처리
    - APIKey          # API 키 변수명도 예외 처리 가능

# 7. SwiftLint 실행 결과 출력 형식
reporter: "xcode"       # 결과를 Xcode 콘솔에서 볼 수 있도록 설정 (json, markdown 등 가능)